# Generated by Django 4.2.20 on 2025-04-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Physics', 'B.Sc. Physics'), ('Chemistry', 'B.Sc. Chemistry'), ('Electronics', 'B.Sc. Electronics'), ('Math', 'B.Sc. Mathematics'), ('CS', 'Computer Science'), ('BioMed', 'Biomedical Science'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('BCom', 'B.Com')], max_length=50)),
                ('photo', models.ImageField(upload_to='faculty_photos/')),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('caste_category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parent_mobile_number', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('same_address', models.BooleanField(default=False)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('last_school_name', models.CharField(max_length=100)),
                ('last_class_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('board_name', models.CharField(max_length=100)),
                ('marks_obtained', models.FloatField()),
                ('percentage', models.FloatField()),
                ('subjects_studied', models.TextField()),
                ('course_applying_for', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('BSC', 'B.Sc.')], max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('medium_of_instruction', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('admission_category', models.CharField(choices=[('General', 'General'), ('Reserved', 'Reserved')], max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('aadhar_card', models.FileField(upload_to='aadhar_cards/')),
                ('hostel_required', models.BooleanField(default=False)),
                ('transport_required', models.BooleanField(default=False)),
                ('scholarship_applied', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
