# Generated by Django 4.2.20 on 2025-04-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='same_address',
        ),
    ]
